class Locators:
    forgot_password_error = "//div[contains(text(),'Please tr')]"
    forgot_password_link = "_97w4"
    address_field = "//input[@id='identify_email']"
    search_button = "//button[@id='did_submit']"
    url = "https://www.facebook.com/"
    phone_xpath = "//input[@id='email']"
    pass_xpath = "//input[@id='pass']"
    login_xpath = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/button[1]"
    not_you = "//a[contains(text(),'Not you?')]"
    continue_button = "//button[contains(text(),'Continue')]"
    instruction = "//div[contains(text(),'We sent your code to:')]"
    assert_phone = "//div[contains(text(),'+972539024548')]"
    code_error = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/div[1]/div[2]/div[1]/img[1]"
    code_field = "//input[@id='recovery_code_entry']"
    via_email = "//div[contains(text(),'Send code via email')]"
    empty_error = "//div[contains(text(),'Please fill in at least one field')]"